import React from 'react';

export const metadata = {
  title: 'Halo ini params',
  description: 'Generated by create next app',
};

export default function PageWithParams({ params }) {
  return <div>{params.idparams}</div>;
}
